### ISSUE TITLE
pacman-key --populate fails because current time is not accessible in the build container

### ISSUE THREAD

**Issue by jakicoll** [pikvm/pi-builder#10]
I'm trying to `make os BOARD=rpi STAGES="__init__ os __cleanup__"`.

It fails at the `pacman-key --populate archlinuxarm` step:

> Step 22/42 : RUN echo "Server = $REPO_URL/\$arch/\$repo" > /etc/pacman.d/mirrorlist 	&& pacman-key --init 	&& pacman-key --populate archlinuxarm
> [...]
> ==> Appending keys from archlinuxarm.gpg...
> gpg: key B55C5315DCD9EE1A was created 16088 days in the future (time warp or clock problem)

So I got a shell in the intermediate build container and found:

> [root@d5d472cce578 /]# date
> Thu 01 Jan 1970 03:00:00 AM MSK

While in the toolbox, things are fine:
> $ docker run -it pi-builder-arm-toolbox
> [root@c93584cae3b0 /]# date
> Wed Dec 30 04:52:35 PM UTC 2020

I'll try to investigate further, but thought I'd let you know at this point. :)

Thank you for this bright idea on how to automate building these images. I'm currently evaluation different ways and this looks very promising. :+1:

**Comment by mdevaev** [comment]
Hi. This is a known issue, due to a bug in the kernel and / or glibc older version on the host machine. Try to build on ubuntu 20.04 or fresh arch linux.

**Comment by jakicoll** [comment]
Yup, that did the trick. Thanks!
