### ISSUE TITLE
error: failed to initialize alpm library

### ISSUE THREAD

**Issue by btafoya** [pikvm/pi-builder#13]
I cloned the repo, dropped the example config.mk in, and get the below result. I originally hit this issue while using pikvm to build a pi zero image.

And I have attempted to build this on several computers all running Ubuntu 20.04.

ubuntu@UbuntuDev:~/pi-builder$ make rpi3
===== Ensuring toolbox image =====
docker build \
                --rm \
                --tag pi-builder-arm-toolbox \
                 \
                --file toolbox/Dockerfile.root \
        toolbox
Sending build context to Docker daemon  15.36kB
Step 1/6 : FROM archlinux/archlinux:base-devel
 ---> bb1d16ed17e2
Step 2/6 : RUN mkdir -p /etc/pacman.d/hooks     && ln -s /dev/null /etc/pacman.d                                                                                                                                                             /hooks/30-systemd-tmpfiles.hook
 ---> Using cache
 ---> 1ef62ba9ddd3
Step 3/6 : RUN pacman --noconfirm -Syu  && pacman --needed --noconfirm -S      a                                                                                                                                                             rp-scan                 python          parted          dosfstools             r                                                                                                                                                             sync    && (pacman --noconfirm -Sc || true)     && rm -rf /var/cache/pacman/pkg/                                                                                                                                                             *
 ---> Running in 9446a1e948e0
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
The command '/bin/sh -c pacman --noconfirm -Syu         && pacman --needed --noc                                                                                                                                                             onfirm -S               arp-scan                python          parted         d                                                                                                                                                             osfstools               rsync   && (pacman --noconfirm -Sc || true)     && rm -r                                                                                                                                                             f /var/cache/pacman/pkg/*' returned a non-zero code: 255
make: *** [Makefile:197: toolbox] Error 255

Running on Ubuntu 20.04 with the latest docker-ce.

**Comment by mdevaev** [comment]
Duplicate: pikvm/pikvm#172
