### ISSUE TITLE
Trying to make os for Pi Zero W

### ISSUE THREAD

**Issue by Shawn1C** [pikvm/pi-builder#21]
Hello,
I've tried many times to get pikvm to get past the "make os" step but I always get the below output, it looks to trying to get the image from a URL that no longer exists. 

**===== Ensuring base rootfs =====
if [ ! -e ./.cache/base-rootfs-zerow.tar.gz ]; then \
        mkdir -p ./.cache \
        && echo "Signature: 8a477f597d28d172789f06886806bc55" > "./.cache/CACHEDIR.TAG" \
        && curl -L -f http://de3.mirror.archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz -z ./.cache/base-rootfs-zerow.tar.gz -o ./.cache/base-rootfs-zerow.tar.gz \
; fi
Warning: Illegal date format for -z, --time-cond (and not a file name). 
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make[1]: *** [Makefile:276: _rpi_base_rootfs_tgz] Error 22
make[1]: Leaving directory '/home/shawn/os/.pi-builder/v2-hdmi-zerow'
make: *** [Makefile:52: os] Error 2**

**Comment by mdevaev** [comment]
Hello. Pi Zero W is no longer supported. See here: https://www.reddit.com/r/pikvm/comments/sq6e63/zero_w_1_and_rpi_1_endoflife/

**Comment by Shawn1C** [comment]
> Hello. Pi Zero W is no longer supported. See here: https://www.reddit.com/r/pikvm/comments/sq6e63/zero_w_1_and_rpi_1_endoflife/

Thank you
