### ISSUE TITLE
Try to use it pi-builder with raspberry pi os

### ISSUE THREAD

**Issue by majuss** [pikvm/pi-builder#29]
I'am customizing pi-builder to build raspberry pi os instead of arch.
Currently I'am doing this in the makefile: 
```makefile
_rpi_base_rootfs_tgz: # 3rd step in make - downloads base root fs as tgz file not an image
	$(call say,"Ensuring base rootfs")
	if [ ! -e $(_RPI_BASE_ROOTFS_TGZ) ]; then \
		mkdir -p $(_CACHE_DIR) \
		&& cd $(_CACHE_DIR) \
		&& curl -L -f $(_RPI_ROOTFS_URL) -o $(_PIOS_IMAGE_NAME) \
		&& unxz -f $(_PIOS_IMAGE_NAME) \
		&& 7z x -aoa pi_image.img 1.img \
		&& mkdir -p root_fs \
		&& cd root_fs \
		&& 7z x -aoa ../1.img \
		&& rm -rf lib \
		&& ln -s usr/lib lib \
		&& cd ../.. \
		&& chmod -R +x .cache/root_fs/usr/bin/bash \
		&& cd .cache/root_fs \
		&& tar -czf ../.$(_RPI_BASE_ROOTFS_TGZ) * \
		&& echo "Signature: 8a477f597d28d172789f06886806bc55" > "../.$(_CACHE_DIR)/CACHEDIR.TAG" \
	; fi
```

But during OS building I hit a wall with:
```
qemu-arm-static: /lib/ld-linux-armhf.so.3: Invalid ELF image for this architecture
```

Dockerfile inside `.build` looks like this:
```dockerfile
FROM scratch

ADD "common-pi-builder-arm-base-rootfs-rpi4.tgz" /
COPY "qemu-arm-static-orig" "/usr/bin/qemu-arm-static-orig"
COPY "qemu-arm-static" "/usr/bin/qemu-arm-static"
#RUN mkdir -p /etc/pacman.d/hooks \
#	&& ln -s /dev/null /etc/pacman.d/hooks/30-systemd-tmpfiles.hook

ARG BOARD
ENV BOARD $BOARD

ARG ARCH
ENV ARCH $ARCH

ARG LOCALE
ENV LOCALE $LOCALE

ARG TIMEZONE
ENV TIMEZONE $TIMEZONE

ARG REPO_URL
ENV REPO_URL $REPO_URL

ARG PIKVM_REPO_URL
ENV PIKVM_REPO_URL $PIKVM_REPO_URL

ARG PIKVM_REPO_KEY
ENV PIKVM_REPO_KEY $PIKVM_REPO_KEY
# https://lists.gnu.org/archive/html/qemu-devel/2017-10/msg03681.html
SHELL ["/usr/bin/bash"]


RUN echo "foobar---------------------"
```

The error messages appears when I try to run an echo in the last line.

**Comment by mdevaev** [comment]
Hello. Try Raspberry OS 32 bit.

**Comment by majuss** [comment]
`https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2023-02-22/2023-02-21-raspios-bullseye-armhf-lite.img.xz`

This is the image I used, which is armhf -> 32 bit :/

**Comment by mdevaev** [comment]
Which host os / cpu arch do you use?

**Comment by majuss** [comment]
Debian 5.10.0-21-amd64

**Comment by majuss** [comment]
Yes thats mine :) Thank you!

**Comment by mdevaev** [comment]
I didn't manage to figure it out in five minutes, I have to leave now, I'll figure it out within a day or two.

**Comment by majuss** [comment]
> I didn't manage to figure it out in five minutes, I have to leave now, I'll figure it out within a day or two.

Did you had a chance to tinker with it?

**Comment by mdevaev** [comment]
I'm doing it now

**Comment by mdevaev** [comment]
I found out what the reason is, but I suggest you find the way to fix it yourself :) 

`7z x -aoa pi_image.img 1.img`

You unzip the image using 7z and because of this, the file access rights structure inside rootfs and all symbolic links are completely broken, because 7z does not support this (or another combination of options is needed). All these things with ld* require the right structure to start.

**Comment by mdevaev** [comment]
How it's going?

**Comment by majuss** [comment]
I pushed my latest code. The builder runs through. I created the tar.gz by extracting the partitions via dd and then mounting it and simply copy everything over and run tar to compress it. Before compressing I copied everything from the boot partition of the original raspios image to /boot inside of the root fs.
The installer etc. went through but the pi wont boot. I guess I have to adjust some size values regarding the partitions? If I remember correctly I had errors while copying files from the boot partition, maybe I should use rsync? Is it safer for these jobs? I will write a short bashscript to do create the tar.gz and then later on move it to the priveleged container.

**Comment by mdevaev** [comment]
There should be no copying errors. Show me the log.

**Comment by majuss** [comment]
So I added my script to build the image: https://github.com/majuss/pi-builder/blob/master/build_iamge.sh
I then copy the resulting tar.gz to the root of pi-builder/ and run `make os BOARD=rpi4 STAGES="__init__ os"` and then `make install`
I put back the sdcard into my pi and tried to boot. But it just outputs a black image. @mdevaev

**Comment by majuss** [comment]
I booted successfully. In `/etc/fstab` and `/boot/cmdline.txt` was a wrong PARTUUID. Any idea how to fix these accordingly to the value which `blkid` offers?

**Comment by mdevaev** [comment]
I dunno but I recommend to use LABEL instead of PARTUUID

**Comment by majuss** [comment]
Found the problem, I need to keep the image name conistant through the whole process. 

So how can I use you builder for x64?

**Comment by mdevaev** [comment]
You mean ARM64?

**Comment by majuss** [comment]
Yes sorry you're right!

**Comment by mdevaev** [comment]
I didn't try it. It should work but boot hacks need to be changed

**Comment by mdevaev** [comment]
Sup. How it is now?

**Comment by mdevaev** [comment]
Did you try making filesystem manually and copy your files to it? Is it working at all?

**Comment by majuss** [comment]
Yep copied everything manually. Nothing at all is happening when I plug in the power to the pi. Only the red LED is turning on, thats it.

**Comment by majuss** [comment]
Seems like my Pi just died... I ordered a new one and will report back.

**Comment by majuss** [comment]
Meanwhile I tried 64 bit. While installing with apt inside of the virtualized OS I encounter this error:
```
8.036 qemu-aarch64-static: /usr/bin/python3.9: requires virtual address space that is in use (omit the -B option or choose a different value)
```

**Comment by mdevaev** [comment]
You need to use qemu-wrapper.c to build a reapper with this option, and place it instead of regular qemu. See makefile.

**Comment by mdevaev** [comment]
Sup. I made a framework for building Raspberry OS, all the basic functions work. Now you can add your stages and do whatever you need. Just reclone repo for new release and try it with this `config.mk`:

```Makefile
OS = rpios
ARCH = aarch64 # For 64-bit
BOARD = rpi4
```

```
make os
make image
```
