### ISSUE TITLE
docker-extract

### ISSUE THREAD

**Issue by faddat** [pikvm/pi-builder#8]
# JSON Parse issue

* https://gitlab.com/blurt/blurt/-/jobs/897394271#L6583
* https://github.com/faddat/sos/runs/1515622615?check_suite_focus=true#step:6:901

But the thing is I haven't been able to figure out what is different about these two images as compared to the other ones.

I'll keep looking into it :)

# Possible solutions?
* https://github.com/ForAllSecure/rootfs_builder
* https://chromium.googlesource.com/external/github.com/docker/containerd/+/refs/tags/v0.2.0/docs/bundle.md (preferred)

**Comment by mdevaev** [comment]
For some reason, this image contains two manifestos. Why might this be the case?

**Comment by faddat** [comment]
Not sure, but I bet that's the trouble.  Thanks for noticing, I will try and figure that out :).

Oh, could it be because I was using a builder image like this:

https://gitlab.com/blurt/blurt/-/blob/armnew/megadrive/Dockerfile

?

I think that is the common thread between both.  For simplicity's sake I'll just make them dependent build jobs.  Thank you!

**Comment by faddat** [comment]
So you know, I'm going to close this for now and I greatly appreciate your help figuring out what the issue was.

**Comment by mdevaev** [comment]
:ok_hand:

**Comment by faddat** [comment]
That did not work.  

All right so here's the situation:

It's crushing my mind.

https://github.com/faddat/sos/blob/master/full/Dockerfile <- works

https://github.com/faddat/sos/blob/c86ecae26a198f90c6e33842644cc7de51d665fa/odroid-c2/build.sh#L23-L29 <- might replace docker-extract

https://gitlab.com/blurt/blurt/-/blob/c74f52022732d3e1db26dd85c74602ef34d11109/megadrive/Dockerfile <- does not work

**Comment by faddat** [comment]
ehhhhhhh still don't know what it is/was exactly.

CI is green now though.

**Comment by mdevaev** [comment]
I sometimes run into strange CI issues on github. Something should work, but doesn't work with strange errors.
